import { blogImages } from "@assets/blog-images";
import { BlogCardType } from "@types";

export const blogCards: BlogCardType[] = [
  {
    image: blogImages.p1,
    id: "1",
    date: "22 june 2022",
    title: "Staffing software: key capabilities and top products",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 481,
    tags: ["Data", "Future"],
  },
  {
    image: blogImages.p2,
    id: "2",
    date: "22 june 2022",
    title: "2022 software development trends explained with benefits",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 400,
    tags: ["App", "Management"],
  },
  {
    image: blogImages.p3,
    id: "3",
    date: "22 june 2022",
    title: "Business analysis helps you in finance",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 300,
    tags: ["CMR", "Big data"],
  },
  {
    image: blogImages.p4,
    id: "4",
    date: "22 june 2022",
    title: "Benefits of telemedicine in nursing homes",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 200,
    tags: ["Media", "Future"],
  },
  {
    image: blogImages.p5,
    id: "5",
    date: "22 june 2022",
    title: "5 web portal examples your business can learn from",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 11,
    tags: ["CIO", "Startup"],
  },
  {
    image: blogImages.p6,
    id: "6",
    date: "22 june 2022",
    title: "Data lake vs. data warehouse: why you don’t have to choose",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 333,
    tags: ["Team", "Data"],
  },
  {
    image: blogImages.p7,
    id: "7",
    date: "22 june 2022",
    title: "Small business gets big data benefits with 3 data sources",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 444,
    tags: ["Data", "Future"],
  },
  {
    image: blogImages.p8,
    id: "8",
    date: "22 june 2022",
    title: "40 stats and real-life examples of how companies use big data",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 481,
    tags: ["App", "Management"],
  },
  {
    image: blogImages.p9,
    id: "9",
    date: "22 june 2022",
    title: "Dirty, clean or cleanish: what’s the quality of your big data?",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    author: "William Pond",
    views: 481,
    tags: ["CIO", "Data"],
  },
];
