import { members } from "@assets/members";

const description =
  "Phasellus tristique eu nisl eu consectetur. Morbi urna massa, imperdiet in mauris et, euismod vestibulum lacus. Integer enim elit, tincidunt aliquam ligula id, lacinia auctor orci. Sed quis lobortis eros. Fusce id commodo libero. At vero eos et accusamus et iusto odio dignissimos ducimus.";

const links = {
  twitter: "https://twitter.com/elonmusk",
  linkedin: "https://www.linkedin.com/in/kiryl-kashavar-1a91951a9/",
  facebook: "https://www.facebook.com/zuck",
};

export const membersCardsFull = {
  en: [
    {
      id: "1",
      image: members.sargis,
      role: "Data analyst",
      name: "Sargis Grigor",
      description,
      links,
    },
    {
      id: "2",
      image: members.bagrat,
      role: "Data engineer",
      name: "Bagrat Leo",
      description,
      links,
    },
    {
      id: "3",
      image: members.gor,
      role: "Data analyst",
      name: "Gor Sargis",
      description,
      links,
    },
    {
      id: "4",
      image: members.mari,
      role: "Data analyst",
      name: "Maral Mari",
      description,
      links,
    },
    {
      id: "5",
      image: members.hacob,
      role: "Data engineer",
      name: "Hakob Jirair",
      description,
      links,
    },
    {
      id: "6",
      image: members.eva,
      role: "Data scientist ",
      name: "Eva Vosgi",
      description,
      links,
    },
    {
      id: "7",
      image: members.marine,
      role: "Data scientist",
      name: "Kohar Marine",
      description,
      links,
    },
    {
      id: "8",
      image: members.ararat,
      role: "Data analyst",
      name: "Ararat Ohannes",
      description,
      links,
    },
    {
      id: "9",
      image: members.eduard,
      role: "Data scientist",
      name: "Eduard Vosgi",
      description,
      links,
    },
  ],

  ru: [
    {
      id: "1",
      image: members.sargis,
      role: "Data analyst",
      name: "Sargis Grigor",
      description,
      links,
    },
    {
      id: "2",
      image: members.bagrat,
      role: "Data engineer",
      name: "Bagrat Leo",
      description,
      links,
    },
    {
      id: "3",
      image: members.gor,
      role: "Data analyst",
      name: "Gor Sargis",
      description,
      links,
    },
    {
      id: "4",
      image: members.mari,
      role: "Data analyst",
      name: "Maral Mari",
      description,
      links,
    },
    {
      id: "5",
      image: members.hacob,
      role: "Data engineer",
      name: "Hakob Jirair",
      description,
      links,
    },
    {
      id: "6",
      image: members.eva,
      role: "Data scientist ",
      name: "Eva Vosgi",
      description,
      links,
    },
    {
      id: "7",
      image: members.marine,
      role: "Data scientist",
      name: "Kohar Marine",
      description,
      links,
    },
    {
      id: "8",
      image: members.ararat,
      role: "Data analyst",
      name: "Ararat Ohannes",
      description,
      links,
    },
    {
      id: "9",
      image: members.eduard,
      role: "Data scientist",
      name: "Eduard Vosgi",
      description,
      links,
    },
  ],
};
