import { miniImagePeople } from "@assets/people/mini";

export const testimonialsCards = {
  en: [
    {
      id: "1",
      image: miniImagePeople.Alex,
      name: "Alex Bern",
      role: "CEO by PixelPerfect",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
    {
      id: "2",
      image: miniImagePeople.Tigran,
      name: "Tigran Nazaret",
      role: "Data analyst",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
    {
      id: "3",
      image: miniImagePeople.Ruben,
      name: "Ruben Chifundo",
      role: "CEO by NOX",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
    {
      id: "4",
      image: miniImagePeople.Alex,
      name: "Alex Bern",
      role: "CEO by PixelPerfect",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
    {
      id: "5",
      image: miniImagePeople.Tigran,
      name: "Tigran Nazaret",
      role: "Data analyst",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
    {
      id: "6",
      image: miniImagePeople.Ruben,
      name: "Ruben Chifundo",
      role: "CEO by NOX",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
    {
      id: "7",
      image: miniImagePeople.Alex,
      name: "Alex Bern",
      role: "CEO by PixelPerfect",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
    {
      id: "8",
      image: miniImagePeople.Tigran,
      name: "Tigran Nazaret",
      role: "Data analyst",
      text: "“Ut enim ad minima veniam, quis nostrum exercitationem ullam corpor suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis utem vel eum iure reprehender qui in ea voluptate velit esse quam nihil molesti consequatur, vel illum.” ",
    },
  ],

  ru: [
    {
      id: "1",
      image: miniImagePeople.Alex,
      name: "Алекс Берн",
      role: "CEO PixelPerfect",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
    {
      id: "2",
      image: miniImagePeople.Tigran,
      name: "Тигран Назарет",
      role: "Аналитик",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
    {
      id: "3",
      image: miniImagePeople.Ruben,
      name: "Рубен Чифундо",
      role: "CEO NOX",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
    {
      id: "4",
      image: miniImagePeople.Alex,
      name: "Алекс Берн",
      role: "CEO PixelPerfect",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
    {
      id: "5",
      image: miniImagePeople.Tigran,
      name: "Тигран Назарет",
      role: "Аналитик",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
    {
      id: "6",
      image: miniImagePeople.Ruben,
      name: "Рубен Чифундо",
      role: "CEO NOX",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
    {
      id: "7",
      image: miniImagePeople.Alex,
      name: "Alex Bern",
      role: "CEO PixelPerfect",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
    {
      id: "8",
      image: miniImagePeople.Tigran,
      name: "Тигран назарет",
      role: "Аналитик",
      text: "“Разнообразный и богатый опыт дальнейшее развитие различных форм деятельности позволяет выполнять важные задания по разработке новых предложений. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение” ",
    },
  ],
};
